export type ContextPurpose = 'DM_ACTION' | 'NPC_DIALOGUE' | 'PROPOSAL_REPAIR' | 'WORLD_AUTHORING';
export interface ContextWorldProfileView { displayName?: string; description?: string; genre?: string; cosmology?: string; narratorRole?: string; narrationStyle?: string; }
export interface ContextCharacterView { id: string; name: string; title: string; status: string; presenceState?: string; locationId?: string | null; [key: string]: unknown; }
export interface ContextLocationView { id: string; name: string; description: string; status?: string; features?: Array<{ name: string; description: string; state: string }>; }
export interface ContextRuleView { type: string; hardness: string; }
export interface ContextQuestView { id: string; title: string; description: string; status: string; objectiveDescription: string; }
export interface ContextKnowledgeView { subjectType: string; subjectId: string; factPath: string; value: unknown; epistemicStatus: string; confidence: number; observedEpoch: number; observationType: string; }
export interface ContextInteractionTurn { speakerType: 'PLAYER' | 'DM' | 'NPC'; speakerId: string; content: string; epoch: number; }
export interface ContextMemoryEpisode { episodeType: string; text: string; importance: number; epoch: number; locationId?: string | null; participantIds?: string[]; entityIds?: string[]; }
export interface ContextEventView { id: string; type: string; description: string; epoch: number; locationId?: string | null; involvedEntityIds?: string[]; }
export interface ContextNarratorPrivateView { hiddenTruths?: Array<{ id: string; title: string; trueNature: string; trueOwnerId?: string; trueGoal?: string; revealed: boolean }>; }
export interface ContextDiagnostics { estimatedTokens: number; budgetLimit: number; includedCounts: Record<string, number>; droppedCounts: Record<string, number>; }
export interface ContextPacket { version: 1; world: { id: string; name: string; epoch: number; profile?: ContextWorldProfileView; axioms?: Array<{ statement: string; immutable: boolean }>; rules?: ContextRuleView[] }; actor?: ContextCharacterView; scene?: { location?: ContextLocationView; characters: ContextCharacterView[] }; observerKnowledge?: { confirmedFacts: ContextKnowledgeView[]; claims: ContextKnowledgeView[]; rumors: ContextKnowledgeView[]; inferences: ContextKnowledgeView[] }; quests?: ContextQuestView[]; recentInteractions?: ContextInteractionTurn[]; relevantMemories?: ContextMemoryEpisode[]; relevantEvents?: ContextEventView[]; narratorPrivate?: ContextNarratorPrivateView; diagnostics: ContextDiagnostics; }
export interface ContextPolicy { purpose: ContextPurpose; includeWorldProfile: boolean; includeWorldAxioms: boolean; includeWorldRules: boolean; includeActorPrivateState: boolean; includeScene: boolean; observerScope: 'PLAYER' | 'NPC' | 'NONE'; includeQuests: boolean; includeRecentInteractions: boolean; includeEpisodicMemory: boolean; includeWorldEvents: boolean; hiddenTruthAccess: 'NONE' | 'RELEVANT_NARRATOR_PRIVATE' | 'RELEVANT_AUTHORING'; maxEstimatedTokens: number; limits: { recentTurns: number; memories: number; knowledgePerBucket: number; quests: number; events: number; hiddenTruths: number; }; }
export interface ContextRequest { worldId: string; userId: string; sessionId: string; actorId: string; purpose: ContextPurpose; currentEpoch: number; userInput: string; npcId?: string; repairFeedback?: unknown; }
