import { dbManager } from '../persistence/database';
import type { InteractionTurn } from './interactionTypes';
export class InteractionRepository {
  static readonly MAX_OLDER_INTERACTION_CANDIDATES = 500;
  static async appendTurn(turn: InteractionTurn): Promise<void> { const content = turn.content.length > 16_000 ? `${turn.content.slice(0, 15_967)}…[truncated]` : turn.content; await dbManager.run('INSERT INTO interaction_turns (id, world_id, session_id, conversation_type, conversation_id, speaker_type, speaker_id, counterpart_id, content, epoch, outcome_status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [turn.id, turn.worldId, turn.sessionId, turn.conversationType, turn.conversationId, turn.speakerType, turn.speakerId, turn.counterpartId ?? null, content, turn.epoch, turn.outcomeStatus, turn.createdAt]); }
  static async appendExchange(turns: [InteractionTurn, InteractionTurn]): Promise<void> { await dbManager.transaction(async () => { await this.appendTurn(turns[0]); await this.appendTurn(turns[1]); }); }
  static async listRecentTurns(worldId: string, conversationId: string, limit: number): Promise<InteractionTurn[]> { const rows = await dbManager.all<any>('SELECT * FROM interaction_turns WHERE world_id = ? AND conversation_id = ? ORDER BY epoch DESC, created_at DESC LIMIT ?', [worldId, conversationId, limit]); return rows.reverse().map(row => ({ id: row.id, worldId: row.world_id, sessionId: row.session_id, conversationType: row.conversation_type, conversationId: row.conversation_id, speakerType: row.speaker_type, speakerId: row.speaker_id, counterpartId: row.counterpart_id, content: row.content, epoch: row.epoch, outcomeStatus: row.outcome_status, createdAt: row.created_at })); }
  static async listRecentSessionTurns(worldId: string, conversationId: string, sessionId: string, limit: number): Promise<InteractionTurn[]> { const rows = await dbManager.all<any>('SELECT * FROM interaction_turns WHERE world_id = ? AND conversation_id = ? AND session_id = ? ORDER BY epoch DESC, created_at DESC LIMIT ?', [worldId, conversationId, sessionId, limit]); return rows.reverse().map(this.map); }
  static async listRelevantOlderTurns(worldId: string, conversationId: string, sessionId: string, userInput: string, limit: number): Promise<InteractionTurn[]> {
    const rows = await dbManager.all<any>('SELECT * FROM interaction_turns WHERE world_id = ? AND conversation_id = ? AND session_id <> ? ORDER BY epoch DESC, created_at DESC LIMIT ?', [worldId, conversationId, sessionId, this.MAX_OLDER_INTERACTION_CANDIDATES]);
    const terms = userInput.toLowerCase().split(/\W+/).filter(term => term.length > 1);
    return rows.map(this.map).map(turn => ({ turn, score: terms.filter(term => turn.content.toLowerCase().includes(term)).length * 1000 + turn.epoch }))
      .filter(item => item.score >= 1000).sort((a, b) => b.score - a.score || a.turn.id.localeCompare(b.turn.id)).slice(0, limit).map(item => item.turn);
  }
  private static map(row: any): InteractionTurn { return { id: row.id, worldId: row.world_id, sessionId: row.session_id, conversationType: row.conversation_type, conversationId: row.conversation_id, speakerType: row.speaker_type, speakerId: row.speaker_id, counterpartId: row.counterpart_id, content: row.content, epoch: row.epoch, outcomeStatus: row.outcome_status, createdAt: row.created_at }; }
}
